### ISSUE TITLE
Error on clicking submit in dataset

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow-hyrax#10]
Go add 'create new work - dataset' or edit an existing dataset
Fill in the required form values
Upload a file
Click on save

The following error message is displayed on the page, on form submit

undefined method `id' for #<ActionDispatch::Routing::RoutesProxy:0x007fa3adc29270>
```
def objectUuid
    @object.id
 end
```

```
lib/hyrax/notifications/subscribers/build_message.rb:93:in `objectUuid'
lib/hyrax/notifications/subscribers/build_message.rb:31:in `to_message'
lib/hyrax/notifications/subscribers/log.rb:7:in `notify'
lib/hyrax/notifications/subscribers/subscriber.rb:14:in `block (2 levels) in subscribe'
app/controllers/concerns/hyrax/notifications/notifiers.rb:8:in `after_create_response'
```

This error does not occur on dataset edit

**Comment by anusharanganathan** [comment]
Fixed. commit https://github.com/CottageLabs/willow/commit/d3d29f551b053f8d3be5effa6b38ccdf8995794a
