### ISSUE TITLE
Error editing a dataset

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow-hyrax#11]
**undefined method `date' for "24/08/2017":String**

Error's in the following line
```
# date
solr_doc[Solrizer.solr_name('date', :stored_searchable)] = object.date.map { |d| d.date.first }
```
Application trace
```
app/indexers/dataset_indexer.rb:19:in `block (2 levels) in generate_solr_document'
app/indexers/dataset_indexer.rb:19:in `map'
app/indexers/dataset_indexer.rb:19:in `block in generate_solr_document'
app/indexers/dataset_indexer.rb:14:in `tap'
app/indexers/dataset_indexer.rb:14:in `generate_solr_document'
```

**Comment by anusharanganathan** [comment]
No longer able to produce, after fixing https://github.com/CottageLabs/willow-hyrax/issues/6
