### ISSUE TITLE
Fix failing spec features

### ISSUE THREAD

**Issue by anusharanganathan** [CottageLabs/willow-hyrax#7]
Need vcr for AdminSet.find_or_create_default_admin_set_id

stack trace
```
 4) Create a Image a logged in user
     Failure/Error: AdminSet.find_or_create_default_admin_set_id

     VCR::Errors::UnhandledHTTPRequestError:


       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         HEAD http://127.0.0.1:8986/rest/test

       There is currently no cassette in use. There are a few ways
       you can configure VCR to handle this request:

         * If you're surprised VCR is raising this error
           and want insight about how VCR attempted to handle the request,
           you can use the debug_logger configuration option to log more details [1].
         * If you want VCR to record this request and play it back during future test
           runs, you should wrap your test (or this portion of your test) in a
           `VCR.use_cassette` block [2].
         * If you only want VCR to handle requests made while a cassette is in use,
           configure `allow_http_connections_when_no_cassette = true`. VCR will
           ignore this request since it is made when there is no cassette [3].
         * If you want VCR to ignore this request (and others like it), you can
           set an `ignore_request` callback [4].

       [1] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/getting-started
       [3] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/allow-http-connections-when-no-cassette
       [4] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/ignore-request
       ================================================================================
     # /var/lib/gems/2.3.0/gems/vcr-3.0.3/lib/vcr/request_handler.rb:97:in `on_unhandled_request'
     # /var/lib/gems/2.3.0/gems/vcr-3.0.3/lib/vcr/library_hooks/webmock.rb:129:in `on_unhandled_request'
     # /var/lib/gems/2.3.0/gems/vcr-3.0.3/lib/vcr/request_handler.rb:24:in `handle'
     # /var/lib/gems/2.3.0/gems/vcr-3.0.3/lib/vcr/library_hooks/webmock.rb:144:in `block in <module:WebMock>'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:28:in `block in register_global_stub'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/request_pattern.rb:36:in `matches?'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `each'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `detect'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `request_stub_for'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:50:in `response_for_request'
     # /var/lib/gems/2.3.0/gems/webmock-3.0.1/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
     # /var/lib/gems/2.3.0/gems/faraday-encoding-0.0.4/lib/faraday/encoding.rb:12:in `call'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
     # /var/lib/gems/2.3.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `head'
     # /var/lib/gems/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:19:in `block in head'
     # /var/lib/gems/2.3.0/gems/ldp-0.7.0/lib/ldp/client/methods.rb:17:in `head'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/initializing_connection.rb:56:in `init_base_path'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/initializing_connection.rb:21:in `head'
     # /var/lib/gems/2.3.0/gems/ldp-0.7.0/lib/ldp/resource.rb:59:in `head'
     # /var/lib/gems/2.3.0/gems/ldp-0.7.0/lib/ldp/resource.rb:42:in `new?'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:195:in `load_from_fedora'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:181:in `find_one'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:234:in `find_with_ids'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:52:in `find'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/finder_methods.rb:85:in `exists?'
     # /var/lib/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/querying.rb:3:in `exists?'
     # /home/ubuntu/.bundle/ruby/2.3.0/hyrax-87188b200feb/app/models/admin_set.rb:59:in `find_or_create_default_admin_set_id'
     # ./spec/features/create_image_spec.rb:17:in `block (3 levels) in <top (required)>'
```

**Comment by martyn-w** [comment]
Now fixed
